SELECT
    p.ID AS PROJECT_ID,
    c.NAME AS CLIENT_NAME,
    SUM(w.SALARY) * DATEDIFF('MONTH', p.START_DATE, p.FINISH_DATE) AS PROJECT_COST
FROM
    project p
JOIN
    client c ON p.CLIENT_ID = c.ID
JOIN
    project_worker pw ON p.ID = pw.PROJECT_ID
JOIN
    worker w ON pw.WORKER_ID = w.ID
GROUP BY
    p.ID, c.NAME
ORDER BY
    PROJECT_COST DESC;
